/* =========================================================================
   GALERIA-DADOS.JS — Lista de fotografias do portefólio
   -------------------------------------------------------------------------
   Gerado a partir das fotografias reais da Timorgiana.
   Cada item: { src: caminho, cat: categoria }
   Categorias: casamentos · vaso · bouquet · funebre · outro
   Para recategorizar uma foto, mude o 'cat'. Para a esconder, apague a
   linha. Para adicionar fotos, coloque a imagem na pasta da categoria em
   assets/galeria/<categoria>/ e acrescente uma linha aqui.
   ========================================================================= */
window.App = window.App || {};
App.GALERIA = [
  { src: "assets/galeria/casamentos/cas-01.jpg", cat: "casamentos" },
  { src: "assets/galeria/casamentos/cas-02.jpg", cat: "casamentos" },
  { src: "assets/galeria/casamentos/cas-03.jpg", cat: "casamentos" },
  { src: "assets/galeria/casamentos/cas-04.jpg", cat: "casamentos" },
  { src: "assets/galeria/casamentos/cas-05.jpg", cat: "casamentos" },
  { src: "assets/galeria/casamentos/cas-06.jpg", cat: "casamentos" },
  { src: "assets/galeria/casamentos/cas-07.jpg", cat: "casamentos" },
  { src: "assets/galeria/bouquet/bouquet-01.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-02.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-03.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-04.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-05.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-06.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-07.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-08.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-09.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-10.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-11.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-12.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-13.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-14.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-15.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-16.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-17.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-18.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-19.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-20.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-21.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-22.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-23.jpg", cat: "bouquet" },
  { src: "assets/galeria/bouquet/bouquet-24.jpg", cat: "bouquet" },
  { src: "assets/galeria/funebre/fun-01.jpg", cat: "funebre" },
  { src: "assets/galeria/outro/outro-01.jpg", cat: "outro" },
  { src: "assets/galeria/outro/outro-02.jpg", cat: "outro" },
  { src: "assets/galeria/outro/outro-03.jpg", cat: "outro" },
  { src: "assets/galeria/vaso/vaso-01.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-02.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-03.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-04.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-05.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-06.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-07.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-08.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-09.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-10.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-11.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-12.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-13.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-14.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-15.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-16.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-17.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-18.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-19.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-20.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-21.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-22.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-23.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-24.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-25.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-26.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-27.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-28.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-29.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-30.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-31.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-32.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-33.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-34.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-35.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-36.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-37.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-38.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-39.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-40.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-41.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-42.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-43.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-44.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-51.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-59.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-60.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-61.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-62.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-63.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-64.jpg", cat: "vaso" },
  { src: "assets/galeria/vaso/vaso-65.jpg", cat: "vaso" },
];
